### ISSUE TITLE
数据库问题

### ISSUE THREAD

**Issue by godsoul** [qieangel2013/zys#1]
数据库驱动层PDO里面有个trace函数没弄干净，mysql驱动里面有大C方法没弄干净，还有一个db方法里，你不管有没有传进config参数，你都读相同的配置了，这样多数据库db切换就不支持了，其他问题暂时还没发现，非常感谢提取出来。

**Comment by qieangel2013** [comment]
已经做了相应的修改，其实db切换已经做了，在配置里做相应的配置就行了，不是说读取相同的配置，只是说读取配置文件是相同的方法

**Comment by cindyming** [comment]
MongoModel  没有这个文件啊
