### ISSUE TITLE
php7下跑视频录制功能无效

### ISSUE THREAD

**Issue by harris-1024** [qieangel2013/zys#6]
只调用了摄像头，live页面空白，消息也发不出去，不知道是哪里出了问题？
版本：php7.0.7 swoole-1.8.7

**Comment by qieangel2013** [comment]
你运行服务端了吗？

**Comment by harris-1024** [comment]
运行了的，代码里只需要改ip为本地地址就可以吧

**Comment by qieangel2013** [comment]
你的服务端可能报错了，你的fd保存在redis里吗？如果不用redis，后台需要运行SwooleLiveServer_table.php这个
